import { ICONS } from "../assets";

export const Urls = {
  SignIn: { name: "Sign In", url: "/auth/sign-in" },
  SignUp: { name: "Sign Up", url: "/auth/sign-up" },
  Home: { name: "Home", url: "/admin" },
  Users: { name: "Users", url: "/admin/users" },
  Products: { name: "Products", url: "/admin/products" },
};

export const MENUITEMS = [
  {
    id: 1,
    label: Urls.Home.name,
    icon: <ICONS.home />,
    path: Urls.Home.url,
  },
  {
    id: 2,
    label: Urls.Users.name,
    icon: <ICONS.users />,
    path: Urls.Users.url,
  },
  {
    id: 3,
    label: Urls.Products.name,
    icon: <ICONS.products />,
    path: Urls.Products.url,
  },
];

export const productlist = [
  {
    id: 0,
    numeric: false,
    disablePadding: true,
    label: 'Product',
  },
  {
    id: 1,
    numeric: true,
    disablePadding: false,
    label: 'Category',
  },
  {
    id: 2,
    numeric: true,
    disablePadding: false,
    label: 'Price',
  },
  {
    id: 3,
    numeric: true,
    disablePadding: false,
    label: 'Stock',
  },
  {
    id: 4,
    numeric: true,
    disablePadding: false,
    label: 'Gender',
  },
  {
    id: 5,
    numeric: true,
    disablePadding: false,
    label: 'Seller',
  },
  {
    id: 6,
    numeric: true,
    disablePadding: false,
    label: 'Published',
  },
  {
    id: 7,
    numeric: true,
    disablePadding: false,
    label: 'Actions',
  },
];

export const productItems = [
  {
    id:0,
    Product: "Hoodie",
    Category: "Clothing",
    Price: "$1,299",
    Stock: 283,
    Gender: "Male",
    Seller: "Apilla.co.in",
    Published: "24,Nov 2022-4:42PM",
    Actions: "edit",
  },
  {
    id:1,
    Product: "T-Shirt",
    Category: "Clothing",
    Price: "$599",
    Stock: 174,
    Gender: "Female",
    Seller: "FashionHub.com",
    Published: "25, Nov 2022 - 1:15 PM",
    Actions: "edit",
  },
  {
    id:2,
    Product: "Sneakers",
    Category: "Footwear",
    Price: "$999",
    Stock: 96,
    Gender: "Male",
    Seller: "FootLocker.com",
    Published: "25, Nov 2022 - 2:30 PM",
    Actions: "edit",
  },
  {
    id:3,
    Product: "Jeans",
    Category: "Clothing",
    Price: "$1,199",
    Stock: 189,
    Gender: "Male",
    Seller: "StyleRUs.com",
    Published: "26, Nov 2022 - 10:20 AM",
    Actions: "edit",
  },
  {
    id:4,
    Product: "Sweater",
    Category: "Clothing",
    Price: "$899",
    Stock: 247,
    Gender: "Female",
    Seller: "FashionCraze.com",
    Published: "27, Nov 2022 - 3:55 PM",
    Actions: "edit",
  },
  {
    id:5,
    Product: "Running Shoes",
    Category: "Footwear",
    Price: "$799",
    Stock: 112,
    Gender: "Female",
    Seller: "ActiveSports.com",
    Published: "28, Nov 2022 - 9:40 AM",
    Actions: "edit",
  },
  {
    id:6,
    Product: "Backpack",
    Category: "Accessories",
    Price: "$799",
    Stock: 86,
    Gender: "Unisex",
    Seller: "BackpackWorld.com",
    Published: "29, Nov 2022 - 11:30 AM",
    Actions: "edit",
  },
  {
    id:7,
    Product: "Jacket",
    Category: "Clothing",
    Price: "$1,499",
    Stock: 163,
    Gender: "Male",
    Seller: "FashionHub.com",
    Published: "30, Nov 2022 - 2:15 PM",
    Actions: "edit",
  },
  {
    id:8,
    Product: "Dress",
    Category: "Clothing",
    Price: "$1,099",
    Stock: 221,
    Gender: "Female",
    Seller: "ChicStyle.com",
    Published: "1, Dec 2022 - 5:20 PM",
    Actions: "edit",
  },
  {
    id:9,
    Product: "Wristwatch",
    Category: "Accessories",
    Price: "$599",
    Stock: 58,
    Gender: "Unisex",
    Seller: "TimePieces.com",
    Published: "2, Dec 2022 - 8:10 AM",
    Actions: "edit",
  },
];

